### PR TITLE
Improve reusability of program

### PR DESCRIPTION
**Pull request by czs108**
- Support Microsoft Visual C++
- Support multiparse
- Support object copy, move and assignment

### CODE REVIEW

**Comment by susilehtola** [comment]
I'm getting a bunch of errors from the patch with GCC 9
```
cmdline.cpp:7:17: error: redefinition of ‘std::string cmdline::detail::demangle(const string&)’
    7 |     std::string demangle(const std::string &name)
      |                 ^~~~~~~~
In file included from cmdline.cpp:1:
cmdline.h:113:27: note: ‘std::string cmdline::detail::demangle(const string&)’ previously defined here
  113 | static inline std::string demangle(const std::string &name)
      |                           ^~~~~~~~
cmdline.cpp:21:3: error: redefinition of ‘cmdline::cmdline_error::cmdline_error(const string&)’
   21 |   cmdline_error::cmdline_error(const std::string &msg)
      |   ^~~~~~~~~~~~~
In file included from cmdline.cpp:1:
cmdline.h:150:3: note: ‘cmdline::cmdline_error::cmdline_error(const string&)’ previously defined here
  150 |   cmdline_error(const std::string &message): msg(message){}
      |   ^~~~~~~~~~~~~
cmdline.cpp:26:3: error: redefinition of ‘cmdline::cmdline_error::~cmdline_error()’
   26 |   cmdline_error::~cmdline_error() = default;
      |   ^~~~~~~~~~~~~
In file included from cmdline.cpp:1:
cmdline.h:151:3: note: ‘virtual cmdline::cmdline_error::~cmdline_error()’ previously defined here
  151 |   ~cmdline_error() throw() {}
      |   ^
cmdline.cpp:28:15: error: redefinition of ‘const char* cmdline::cmdline_error::what() const’
   28 |   const char *cmdline_error::what() const
      |               ^~~~~~~~~~~~~
In file included from cmdline.cpp:1:
cmdline.h:152:15: note: ‘virtual const char* cmdline::cmdline_error::what() const’ previously defined here
  152 |   const char *what() const throw() { return msg.c_str(); }
      |               ^~~~
cmdline.cpp:33:3: error: redefinition of ‘cmdline::parser::parser()’
   33 |   parser::parser() = default;
      |   ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:324:3: note: ‘cmdline::parser::parser()’ previously defined here
  324 |   parser(){
      |   ^~~~~~
cmdline.cpp:35:3: error: redefinition of ‘cmdline::parser::parser(const cmdline::parser&)’
   35 |   parser::parser(const parser &obj)
      |   ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:327:3: note: ‘cmdline::parser::parser(const cmdline::parser&)’ previously defined here
  327 |   parser(const parser &obj) {
      |   ^~~~~~
cmdline.cpp:40:3: error: redefinition of ‘cmdline::parser::parser(cmdline::parser&&)’
   40 |   parser::parser(parser &&obj)
      |   ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:331:3: note: ‘cmdline::parser::parser(cmdline::parser&&)’ previously defined here
  331 |   parser(parser &&obj) {
      |   ^~~~~~
cmdline.cpp:45:11: error: redefinition of ‘cmdline::parser& cmdline::parser::operator=(const cmdline::parser&)’
   45 |   parser &parser::operator=(const parser &obj)
      |           ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:335:11: note: ‘cmdline::parser& cmdline::parser::operator=(const cmdline::parser&)’ previously defined here
  335 |   parser &operator=(const parser &obj) {
      |           ^~~~~~~~
cmdline.cpp:51:11: error: redefinition of ‘cmdline::parser& cmdline::parser::operator=(cmdline::parser&&)’
   51 |   parser &parser::operator=(parser &&obj)
      |           ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:340:11: note: ‘cmdline::parser& cmdline::parser::operator=(cmdline::parser&&)’ previously defined here
  340 |   parser &operator=(parser &&obj) {
      |           ^~~~~~~~
cmdline.cpp:57:3: error: redefinition of ‘cmdline::parser::~parser()’
   57 |   parser::~parser()
      |   ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:345:3: note: ‘cmdline::parser::~parser()’ previously defined here
  345 |   ~parser(){
      |   ^
cmdline.cpp:67:8: error: redefinition of ‘void cmdline::parser::add(const string&, char, const string&)’
   67 |   void parser::add(const std::string &name,
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:360:8: note: ‘void cmdline::parser::add(const string&, char, const string&)’ previously defined here
  360 |   void add(const std::string &name,
      |        ^~~
cmdline.cpp:82:8: error: redefinition of ‘bool cmdline::parser::exist(const string&) const’
   82 |   bool parser::exist(const std::string &name) const
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:397:8: note: ‘bool cmdline::parser::exist(const string&) const’ previously defined here
  397 |   bool exist(const std::string &name) const {
      |        ^~~~~
cmdline.cpp:94:8: error: no declaration matches ‘bool cmdline::parser::parse_check(const string&)’
   94 |   bool parser::parse_check(const std::string &arg)
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:578:8: note: candidates are: ‘void cmdline::parser::parse_check(int, char**)’
  578 |   void parse_check(int argc, char *argv[]){
      |        ^~~~~~~~~~~
cmdline.h:572:8: note:                 ‘void cmdline::parser::parse_check(const std::vector<std::__cxx11::basic_string<char> >&)’
  572 |   void parse_check(const std::vector<std::string> &args){
      |        ^~~~~~~~~~~
cmdline.h:566:8: note:                 ‘void cmdline::parser::parse_check(const string&)’
  566 |   void parse_check(const std::string &arg){
      |        ^~~~~~~~~~~
cmdline.h:322:7: note: ‘class cmdline::parser’ defined here
  322 | class parser{
      |       ^~~~~~
cmdline.cpp:104:8: error: no declaration matches ‘bool cmdline::parser::parse_check(const std::vector<std::__cxx11::basic_string<char> >&)’
  104 |   bool parser::parse_check(const std::vector<std::string> &args)
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:578:8: note: candidates are: ‘void cmdline::parser::parse_check(int, char**)’
  578 |   void parse_check(int argc, char *argv[]){
      |        ^~~~~~~~~~~
cmdline.h:572:8: note:                 ‘void cmdline::parser::parse_check(const std::vector<std::__cxx11::basic_string<char> >&)’
  572 |   void parse_check(const std::vector<std::string> &args){
      |        ^~~~~~~~~~~
cmdline.h:566:8: note:                 ‘void cmdline::parser::parse_check(const string&)’
  566 |   void parse_check(const std::string &arg){
      |        ^~~~~~~~~~~
cmdline.h:322:7: note: ‘class cmdline::parser’ defined here
  322 | class parser{
      |       ^~~~~~
cmdline.cpp:114:8: error: no declaration matches ‘bool cmdline::parser::parse_check(int, char**)’
  114 |   bool parser::parse_check(int argc, char *argv[])
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:578:8: note: candidates are: ‘void cmdline::parser::parse_check(int, char**)’
  578 |   void parse_check(int argc, char *argv[]){
      |        ^~~~~~~~~~~
cmdline.h:572:8: note:                 ‘void cmdline::parser::parse_check(const std::vector<std::__cxx11::basic_string<char> >&)’
  572 |   void parse_check(const std::vector<std::string> &args){
      |        ^~~~~~~~~~~
cmdline.h:566:8: note:                 ‘void cmdline::parser::parse_check(const string&)’
  566 |   void parse_check(const std::string &arg){
      |        ^~~~~~~~~~~
cmdline.h:322:7: note: ‘class cmdline::parser’ defined here
  322 | class parser{
      |       ^~~~~~
cmdline.cpp:124:15: error: redefinition of ‘std::string cmdline::parser::usage() const’
  124 |   std::string parser::usage() const
      |               ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:595:15: note: ‘std::string cmdline::parser::usage() const’ previously defined here
  595 |   std::string usage() const {
      |               ^~~~~
cmdline.cpp:168:15: error: redefinition of ‘std::string cmdline::parser::error_full() const’
  168 |   std::string parser::error_full() const
      |               ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:588:15: note: ‘std::string cmdline::parser::error_full() const’ previously defined here
  588 |   std::string error_full() const{
      |               ^~~~~~~~~~
cmdline.cpp:179:8: error: redefinition of ‘bool cmdline::parser::parse(const string&)’
  179 |   bool parser::parse(const std::string &arg)
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:414:8: note: ‘bool cmdline::parser::parse(const string&)’ previously defined here
  414 |   bool parse(const std::string &arg){
      |        ^~~~~
cmdline.cpp:232:8: error: redefinition of ‘bool cmdline::parser::parse(const std::vector<std::__cxx11::basic_string<char> >&)’
  232 |   bool parser::parse(const std::vector<std::string> &args)
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:456:8: note: ‘bool cmdline::parser::parse(const std::vector<std::__cxx11::basic_string<char> >&)’ previously defined here
  456 |   bool parse(const std::vector<std::string> &args){
      |        ^~~~~
cmdline.cpp:249:8: error: redefinition of ‘bool cmdline::parser::parse(int, const char* const*)’
  249 |   bool parser::parse(int argc, const char *const argv[])
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:466:8: note: ‘bool cmdline::parser::parse(int, const char* const*)’ previously defined here
  466 |   bool parse(int argc, const char * const argv[]){
      |        ^~~~~
cmdline.cpp:392:8: error: no declaration matches ‘bool cmdline::parser::check(int, bool)’
  392 |   bool parser::check(int argc, bool ok)
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:655:8: note: candidate is: ‘void cmdline::parser::check(int, bool)’
  655 |   void check(int argc, bool ok){
      |        ^~~~~
cmdline.h:322:7: note: ‘class cmdline::parser’ defined here
  322 | class parser{
      |       ^~~~~~
cmdline.cpp:410:8: error: redefinition of ‘void cmdline::parser::set_option(const string&)’
  410 |   void parser::set_option(const std::string &name)
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:667:8: note: ‘void cmdline::parser::set_option(const string&)’ previously defined here
  667 |   void set_option(const std::string &name){
      |        ^~~~~~~~~~
cmdline.cpp:422:8: error: redefinition of ‘void cmdline::parser::set_option(const string&, const string&)’
  422 |   void parser::set_option(const std::string &name, const std::string &value)
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:678:8: note: ‘void cmdline::parser::set_option(const string&, const string&)’ previously defined here
  678 |   void set_option(const std::string &name, const std::string &value){
      |        ^~~~~~~~~~
cmdline.cpp:434:8: error: redefinition of ‘void cmdline::parser::clear()’
  434 |   void parser::clear()
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:351:8: note: ‘void cmdline::parser::clear()’ previously defined here
  351 |   void clear() {
      |        ^~~~~
cmdline.cpp:445:8: error: redefinition of ‘void cmdline::parser::move_parser(cmdline::parser&, cmdline::parser&)’
  445 |   void parser::move_parser(parser &src, parser &dest)
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:627:8: note: ‘void cmdline::parser::move_parser(cmdline::parser&, cmdline::parser&)’ previously defined here
  627 |   void move_parser(parser &src, parser &dest) {
      |        ^~~~~~~~~~~
cmdline.cpp:460:8: error: redefinition of ‘void cmdline::parser::copy_parser(const cmdline::parser&, cmdline::parser&)’
  460 |   void parser::copy_parser(const parser &src, parser &dest)
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:641:8: note: ‘void cmdline::parser::copy_parser(const cmdline::parser&, cmdline::parser&)’ previously defined here
  641 |   void copy_parser(const parser &src, parser &dest) {
      |        ^~~~~~~~~~~
cmdline.cpp:475:36: error: definition of implicitly-declared ‘constexpr cmdline::parser::option_base::option_base()’
  475 |   parser::option_base::option_base() = default;
      |                                    ^
cmdline.cpp:475:3: error: ‘class cmdline::parser::option_base’ is private within this context
  475 |   parser::option_base::option_base() = default;
      |   ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:689:9: note: declared private here
  689 |   class option_base{
      |         ^~~~~~~~~~~
cmdline.cpp:477:3: error: redefinition of ‘cmdline::parser::option_base::~option_base()’
  477 |   parser::option_base::~option_base() = default;
      |   ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:691:13: note: ‘virtual cmdline::parser::option_base::~option_base()’ previously defined here
  691 |     virtual ~option_base(){}
      |             ^
cmdline.cpp:477:3: error: ‘class cmdline::parser::option_base’ is private within this context
  477 |   parser::option_base::~option_base() = default;
      |   ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:689:9: note: declared private here
  689 |   class option_base{
      |         ^~~~~~~~~~~
cmdline.cpp:479:3: error: redefinition of ‘cmdline::parser::option_without_value::option_without_value(const string&, char, const string&)’
  479 |   parser::option_without_value::option_without_value(
      |   ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:710:5: note: ‘cmdline::parser::option_without_value::option_without_value(const string&, char, const string&)’ previously defined here
  710 |     option_without_value(const std::string &full_name,
      |     ^~~~~~~~~~~~~~~~~~~~
cmdline.cpp:479:3: error: ‘class cmdline::parser::option_without_value’ is private within this context
  479 |   parser::option_without_value::option_without_value(
      |   ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:708:9: note: declared private here
  708 |   class option_without_value : public option_base {
      |         ^~~~~~~~~~~~~~~~~~~~
cmdline.cpp:487:24: error: redefinition of ‘cmdline::parser::option_base* cmdline::parser::option_without_value::clone() const’
  487 |   parser::option_base *parser::option_without_value::clone() const
      |                        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:728:18: note: ‘virtual cmdline::parser::option_base* cmdline::parser::option_without_value::clone() const’ previously defined here
  728 |     option_base *clone() const {
      |                  ^~~~~
cmdline.cpp:487:11: error: ‘class cmdline::parser::option_base’ is private within this context
  487 |   parser::option_base *parser::option_without_value::clone() const
      |           ^~~~~~~~~~~
In file included from cmdline.cpp:1:
cmdline.h:689:9: note: declared private here
  689 |   class option_base{
      |         ^~~~~~~~~~~
cmdline.cpp:487:24: error: ‘class cmdline::parser::option_without_value’ is private within this context
  487 |   parser::option_base *parser::option_without_value::clone() const
      |                        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:708:9: note: declared private here
  708 |   class option_without_value : public option_base {
      |         ^~~~~~~~~~~~~~~~~~~~
cmdline.cpp:494:8: error: redefinition of ‘bool cmdline::parser::option_without_value::has_value() const’
  494 |   bool parser::option_without_value::has_value() const
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:717:10: note: ‘virtual bool cmdline::parser::option_without_value::has_value() const’ previously defined here
  717 |     bool has_value() const { return false; }
      |          ^~~~~~~~~
cmdline.cpp:494:8: error: ‘class cmdline::parser::option_without_value’ is private within this context
  494 |   bool parser::option_without_value::has_value() const
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:708:9: note: declared private here
  708 |   class option_without_value : public option_base {
      |         ^~~~~~~~~~~~~~~~~~~~
cmdline.cpp:499:8: error: redefinition of ‘void cmdline::parser::option_without_value::clear()’
  499 |   void parser::option_without_value::clear()
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:724:10: note: ‘virtual void cmdline::parser::option_without_value::clear()’ previously defined here
  724 |     void clear() {
      |          ^~~~~
cmdline.cpp:499:8: error: ‘class cmdline::parser::option_without_value’ is private within this context
  499 |   void parser::option_without_value::clear()
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:708:9: note: declared private here
  708 |   class option_without_value : public option_base {
      |         ^~~~~~~~~~~~~~~~~~~~
cmdline.cpp:504:8: error: redefinition of ‘bool cmdline::parser::option_without_value::set()’
  504 |   bool parser::option_without_value::set()
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:719:10: note: ‘virtual bool cmdline::parser::option_without_value::set()’ previously defined here
  719 |     bool set(){
      |          ^~~
cmdline.cpp:504:8: error: ‘class cmdline::parser::option_without_value’ is private within this context
  504 |   bool parser::option_without_value::set()
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:708:9: note: declared private here
  708 |   class option_without_value : public option_base {
      |         ^~~~~~~~~~~~~~~~~~~~
cmdline.cpp:510:8: error: redefinition of ‘bool cmdline::parser::option_without_value::set(const string&)’
  510 |   bool parser::option_without_value::set(const std::string &)
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:734:10: note: ‘virtual bool cmdline::parser::option_without_value::set(const string&)’ previously defined here
  734 |     bool set(const std::string &){
      |          ^~~
cmdline.cpp:510:8: error: ‘class cmdline::parser::option_without_value’ is private within this context
  510 |   bool parser::option_without_value::set(const std::string &)
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:708:9: note: declared private here
  708 |   class option_without_value : public option_base {
      |         ^~~~~~~~~~~~~~~~~~~~
cmdline.cpp:515:8: error: redefinition of ‘bool cmdline::parser::option_without_value::has_set() const’
  515 |   bool parser::option_without_value::has_set() const
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:738:10: note: ‘virtual bool cmdline::parser::option_without_value::has_set() const’ previously defined here
  738 |     bool has_set() const {
      |          ^~~~~~~
cmdline.cpp:515:8: error: ‘class cmdline::parser::option_without_value’ is private within this context
  515 |   bool parser::option_without_value::has_set() const
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:708:9: note: declared private here
  708 |   class option_without_value : public option_base {
      |         ^~~~~~~~~~~~~~~~~~~~
cmdline.cpp:520:8: error: redefinition of ‘bool cmdline::parser::option_without_value::valid() const’
  520 |   bool parser::option_without_value::valid() const
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:742:10: note: ‘virtual bool cmdline::parser::option_without_value::valid() const’ previously defined here
  742 |     bool valid() const{
      |          ^~~~~
cmdline.cpp:520:8: error: ‘class cmdline::parser::option_without_value’ is private within this context
  520 |   bool parser::option_without_value::valid() const
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:708:9: note: declared private here
  708 |   class option_without_value : public option_base {
      |         ^~~~~~~~~~~~~~~~~~~~
cmdline.cpp:525:8: error: redefinition of ‘bool cmdline::parser::option_without_value::must() const’
  525 |   bool parser::option_without_value::must() const
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:746:10: note: ‘virtual bool cmdline::parser::option_without_value::must() const’ previously defined here
  746 |     bool must() const{
      |          ^~~~
cmdline.cpp:525:8: error: ‘class cmdline::parser::option_without_value’ is private within this context
  525 |   bool parser::option_without_value::must() const
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:708:9: note: declared private here
  708 |   class option_without_value : public option_base {
      |         ^~~~~~~~~~~~~~~~~~~~
cmdline.cpp:530:22: error: redefinition of ‘const string& cmdline::parser::option_without_value::name() const’
  530 |   const std::string &parser::option_without_value::name() const
      |                      ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:750:24: note: ‘virtual const string& cmdline::parser::option_without_value::name() const’ previously defined here
  750 |     const std::string &name() const{
      |                        ^~~~
cmdline.cpp:530:22: error: ‘class cmdline::parser::option_without_value’ is private within this context
  530 |   const std::string &parser::option_without_value::name() const
      |                      ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:708:9: note: declared private here
  708 |   class option_without_value : public option_base {
      |         ^~~~~~~~~~~~~~~~~~~~
cmdline.cpp:535:8: error: redefinition of ‘char cmdline::parser::option_without_value::short_name() const’
  535 |   char parser::option_without_value::short_name() const
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:754:10: note: ‘virtual char cmdline::parser::option_without_value::short_name() const’ previously defined here
  754 |     char short_name() const{
      |          ^~~~~~~~~~
cmdline.cpp:535:8: error: ‘class cmdline::parser::option_without_value’ is private within this context
  535 |   char parser::option_without_value::short_name() const
      |        ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:708:9: note: declared private here
  708 |   class option_without_value : public option_base {
      |         ^~~~~~~~~~~~~~~~~~~~
cmdline.cpp:540:22: error: redefinition of ‘const string& cmdline::parser::option_without_value::description() const’
  540 |   const std::string &parser::option_without_value::description() const
      |                      ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:758:24: note: ‘virtual const string& cmdline::parser::option_without_value::description() const’ previously defined here
  758 |     const std::string &description() const {
      |                        ^~~~~~~~~~~
cmdline.cpp:540:22: error: ‘class cmdline::parser::option_without_value’ is private within this context
  540 |   const std::string &parser::option_without_value::description() const
      |                      ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:708:9: note: declared private here
  708 |   class option_without_value : public option_base {
      |         ^~~~~~~~~~~~~~~~~~~~
cmdline.cpp:545:15: error: redefinition of ‘std::string cmdline::parser::option_without_value::short_description() const’
  545 |   std::string parser::option_without_value::short_description() const
      |               ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:762:17: note: ‘virtual std::string cmdline::parser::option_without_value::short_description() const’ previously defined here
  762 |     std::string short_description() const{
      |                 ^~~~~~~~~~~~~~~~~
cmdline.cpp:545:15: error: ‘class cmdline::parser::option_without_value’ is private within this context
  545 |   std::string parser::option_without_value::short_description() const
      |               ^~~~~~
In file included from cmdline.cpp:1:
cmdline.h:708:9: note: declared private here
  708 |   class option_without_value : public option_base {
      |         ^~~~~~~~~~~~~~~~~~~~
```

**Comment by czs108** [comment]
Why do you hava a cmdline.cpp file？Only need the cmdline.h，this is template

**Comment by susilehtola** [comment]
Rhetorical question? Lol! This is a pull request you filed, in which you moved instantiations from the header to a cpp file.

I got the errors downloading and applying the patch for the pull request. But, downloading the `cmdline.h` and `cmdline.cpp` from your fork, I have more success: you just need to `#include <cstring>` in `cmdline.cpp`, and redefine `virtual const char* cmdline::cmdline_error::what() const noexcept` to `const char * cmdline::cmdline_error::what() const  _GLIBCXX_TXN_SAFE_DYN _GLIBCXX_NOTHROW`.

Unfortunately, your branch is also suffering from #24.

**Comment by czs108** [comment]
Sorry, this is my file and I forget it, I pulled it a long time ago. I will check the code at a convenient time

**Pull request closed without merging**
